### ISSUE TITLE
I found a possible performance problem🤔.

### ISSUE THREAD

**Issue by ChurchTao** [CrossCopy/tauri-plugin-clipboard#25]
@HuakunShen During use, I found a possible performance problem🤔. When using the API to read the Image or using the listener, I found that when the image is large, the main process will be blocked. This is the blocking time-consuming situation I debugged. It can happen in rust layer.I tried to copy a 4k picture, but the interface was blocked for about 7 seconds and became inoperable.
![image](https://github.com/CrossCopy/tauri-plugin-clipboard/assets/58334417/e12990bf-906b-499b-96ce-42dc894ba467)

_Originally posted by @Tester-957 in https://github.com/CrossCopy/tauri-plugin-clipboard/issues/21#issuecomment-2053622906_

**Comment by ChurchTao** [comment]
I perform performance testing on `clipboard-rs`

**Comment by HuakunShen** [comment]
@ChurchTao How is the performance on `clipboard-rs` without Tauri?

**Comment by HuakunShen** [comment]
My performance results on a 5MB screenshot (2560x2880)

## `clipboard-rs`

### Debug Mode

- `ctx.get_image()`: 88ms
- Get Image + Save to disk: 4.15s

### Release Mode

- `ctx.get_image()`: 88ms
- Get Image + Save to disk: 141ms

## tauri-plugin-clipboard demo

### Debug Mode

- Get clipboard context from mutex + `get_image()`: 1.35s
-  mutex + `get_image()` + convert to bytes: 5.56s
- Total (Display on screen): ~7s

### Release Mode

- Total (Display on screen): ~0.8s


I believe it's fine. In release mode it's really fast.
The blocking problem can be fixed by making the `read_image()` tauri commands async. I will fix it.
